language: python
python:
  - 3.6
script:
  - pytest

notifications:
  email:
    recipients:
      - matiasnferrero@gmail.com
    on_success: never
    on_failure: always

addons:
  artifacts:
    working_dir: "D:/code/da-notebooks/notebooks/_modules"    
